### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by gamerpotion** [SpyMan10/backpackmod-1.16-old#13]
hi, I am using your mod on my modpack - https://www.curseforge.com/minecraft/modpacks/darkrpg

Some users on the server have said there is a duplication bug possible with the backpacks where if you drop it and open together really fast it allows duplication.

Is there an option that can be added to the backpack to disable it from being dropped? 

here is an example of the dupe on another backpack mod - https://youtu.be/a-O6nYfEgVs
but the process is possible on your mod too

**Comment by SpyMan10** [comment]
Hello, please make sure that the item dropped aren't a "ghost item" due to server-side latency.

Thanks for report it

**Comment by gamerpotion** [comment]
> Hello, please make sure that the item dropped aren't a "ghost item" due to server-side latency.
> 
> Thanks for report it

Hi thanks,  yes it applies in singleplayer mode also and dupe bug can be done there.

**Comment by Rav115** [comment]
Example of it done in singleplayer
https://user-images.githubusercontent.com/39887530/179019958-5202d2b4-ca5e-463f-9d43-f7ab7dfcf4ce.mp4

but looks like its something to do with some other mod together with backpack mod cause when disabled all other mods and left only backpack cant seem to replicate it.

but still would be nice to have config to disable that item from droping or force close the bag when your holding ghost of it.
otherwise in future there might be some fishing rods what allow stealing backpacks/items from player inventory making this drop bag dup still possible

i will try to find what mod allows this bug to happen

**Comment by SpyMan10** [comment]
I will fix it as fast as possible please wait few hours

EDIT: Hum so strange, I haven't this problem when try to drop it.
You seems to have a mod who maybe change the default inventory behavior

**Comment by SpyMan10** [comment]
I tried to fix it in version 4.0.2
All should be okay now

**Comment by gamerpotion** [comment]
> I tried to fix it in version 4.0.2 All should be okay now

Thank you, is it possible for 1.18.2 to also get that fix? as we are using that version in the modpack
thanks

**Comment by SpyMan10** [comment]
Done!

use new version `1.18.2-3.2.0`
